change version to 0.9.1
Otherwise pbr is complaining under the mac os
ERROR:
36, in _get_version_from_git_target
        dict(new=new_version, target=target_version))
    ValueError: git history requires a target version of
    pbr.version.SemanticVersion(0.9.1), but target version is
    pbr.version.SemanticVersion(0.9.0)

    error in setup command: Error parsing
    /private/var/folders/_y/2zwzc3xj3y3139p_k4sz867c0000gn/T/pip-req-build-q9_qrtjo/setup.cfg:
    ValueError: git history requires a target version of
    pbr.version.SemanticVersion(0.9.1), but target version is
    pbr.version.SemanticVersion(0.9.0)